import { Merchant, Product, User } from './types'

export const MOCK_USERS: User[] = [
  {
    id: '1',
    name: 'Budi Santoso',
    email: 'budi@example.com',
    phone: '081234567890',
    password: 'password123',
  },
  {
    id: '2',
    name: 'Siti Nurhaliza',
    email: 'siti@example.com',
    phone: '082234567890',
    password: 'password123',
  },
]

export const MOCK_MERCHANTS: Merchant[] = [
  {
    id: 'blacksinyo',
    slug: 'blacksinyo',
    name: 'Blacksinyo Coffee',
    description: 'Specialty coffee experience with a minimalist soul. Every cup crafted with intention, every sip rewarded.',
    logo: 'https://placehold.co/120x120/000000/FFFFFF?text=BS',
    heroImage: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1920&q=80',
    category: 'Specialty Coffee',
    pointsMultiplier: 0.1,
    featured: true,
  },
]

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'bs-1',
    merchantId: 'blacksinyo',
    name: 'Espresso',
    description: 'Pure, concentrated coffee shot with rich crema and bold flavor profile',
    price: 25000,
    image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=600&q=80',
    category: 'Espresso',
    rating: 4.8,
    sold: 3200,
  },
  {
    id: 'bs-2',
    merchantId: 'blacksinyo',
    name: 'Americano',
    description: 'Espresso diluted with hot water for a smooth, full-bodied black coffee',
    price: 30000,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    category: 'Espresso',
    rating: 4.7,
    sold: 2800,
  },
  {
    id: 'bs-3',
    merchantId: 'blacksinyo',
    name: 'Cappuccino',
    description: 'Classic Italian coffee with equal parts espresso, steamed milk and velvety microfoam',
    price: 35000,
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=600&q=80',
    category: 'Espresso',
    rating: 4.9,
    sold: 4100,
  },
  {
    id: 'bs-4',
    merchantId: 'blacksinyo',
    name: 'Caffe Latte',
    description: 'Smooth espresso with velvety steamed milk and a delicate layer of foam',
    price: 38000,
    image: 'https://images.unsplash.com/photo-1561047029-3000c68339ca?auto=format&fit=crop&w=600&q=80',
    category: 'Espresso',
    rating: 4.8,
    sold: 3900,
  },
  {
    id: 'bs-5',
    merchantId: 'blacksinyo',
    name: 'Caramel Macchiato',
    description: 'Vanilla-infused milk marked with espresso and a generous drizzle of caramel',
    price: 42000,
    image: 'https://images.unsplash.com/photo-1485808191679-5f86510bd9d5?auto=format&fit=crop&w=600&q=80',
    category: 'Specialty',
    rating: 4.9,
    sold: 5600,
  },
  {
    id: 'bs-6',
    merchantId: 'blacksinyo',
    name: 'Cold Brew',
    description: 'Slow-steeped for 18 hours — smooth, naturally sweet, served over ice',
    price: 40000,
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=600&q=80',
    category: 'Cold',
    rating: 4.8,
    sold: 2200,
  },
  {
    id: 'bs-7',
    merchantId: 'blacksinyo',
    name: 'Matcha Latte',
    description: 'Premium Japanese matcha whisked with steamed milk for a creamy, earthy delight',
    price: 45000,
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99eb4b174?auto=format&fit=crop&w=600&q=80',
    category: 'Specialty',
    rating: 4.7,
    sold: 1900,
  },
  {
    id: 'bs-8',
    merchantId: 'blacksinyo',
    name: 'Iced Chocolate',
    description: 'Rich Belgian chocolate blended with cold milk for ultimate indulgence',
    price: 38000,
    image: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=600&q=80',
    category: 'Cold',
    rating: 4.6,
    sold: 1750,
  },
  {
    id: 'bs-9',
    merchantId: 'blacksinyo',
    name: 'Butter Croissant',
    description: 'Flaky, golden croissant made with French butter and laminated to perfection',
    price: 32000,
    image: 'https://images.unsplash.com/photo-1555507036-ab794f4afe5e?auto=format&fit=crop&w=600&q=80',
    category: 'Pastry',
    rating: 4.8,
    sold: 3400,
  },
  {
    id: 'bs-10',
    merchantId: 'blacksinyo',
    name: 'Banana Bread',
    description: 'Moist, dense banana bread with toasted walnuts, served warm',
    price: 28000,
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=600&q=80',
    category: 'Pastry',
    rating: 4.6,
    sold: 1800,
  },
  {
    id: 'bs-11',
    merchantId: 'blacksinyo',
    name: 'Cheesecake',
    description: 'Creamy New York-style cheesecake on a buttery graham cracker crust',
    price: 45000,
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=600&q=80',
    category: 'Pastry',
    rating: 4.9,
    sold: 2600,
  },
  {
    id: 'bs-12',
    merchantId: 'blacksinyo',
    name: 'Tiramisu',
    description: 'Classic Italian dessert with espresso-soaked ladyfingers and mascarpone cream',
    price: 48000,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=600&q=80',
    category: 'Pastry',
    rating: 4.9,
    sold: 2100,
  },
]

export const MOCK_USER_POINTS_DATA = {
  totalPoints: 3800,
  availablePoints: 3800,
  redeemedPoints: 0,
}

export const MOCK_TRANSACTIONS = [
  {
    id: 'trans-1',
    userId: '1',
    merchantId: 'blacksinyo',
    merchantName: 'Blacksinyo Coffee',
    amount: 77000,
    pointsEarned: 770,
    timestamp: new Date('2024-04-20'),
    items: [
      { productName: 'Caramel Macchiato', quantity: 1, price: 42000 },
      { productName: 'Butter Croissant', quantity: 1, price: 32000 },
    ],
  },
  {
    id: 'trans-2',
    userId: '1',
    merchantId: 'blacksinyo',
    merchantName: 'Blacksinyo Coffee',
    amount: 115000,
    pointsEarned: 1150,
    timestamp: new Date('2024-04-18'),
    items: [
      { productName: 'Cappuccino', quantity: 2, price: 35000 },
      { productName: 'Cheesecake', quantity: 1, price: 45000 },
    ],
  },
  {
    id: 'trans-3',
    userId: '1',
    merchantId: 'blacksinyo',
    merchantName: 'Blacksinyo Coffee',
    amount: 124000,
    pointsEarned: 1240,
    timestamp: new Date('2024-04-15'),
    items: [
      { productName: 'Caffe Latte', quantity: 2, price: 38000 },
      { productName: 'Tiramisu', quantity: 1, price: 48000 },
    ],
  },
]
